These are the instructions:

```{r}
# Load other packages here.
if (!require("tidyverse")) install.packages("tidyverse"); library(tidyverse)

knitr::opts_chunk$set(echo = TRUE)
if (!require("UsingR")) install.packages("UsingR"); library(UsingR)
if (!require("cowplot")) install.packages("cowplot"); library(cowplot)
if (!require("car")) install.packages("car"); library(car) # Anova function for better lm summary stats
if (!require("multcomp")) install.packages("multcomp"); library(multcomp) # glht function for Tukey test
if (!require("emmeans")) install.packages("emmeans"); library(emmeans) # emmeans and pairs functions for post-hoc analysis
if (!require("conflicted")) install.packages("conflicted"); library(conflicted) # For dealing with conflicts
if (!require("tidyverse")) install.packages("tidyverse"); library(tidyverse) # For everything
conflict_prefer_all("dplyr", quiet = TRUE)
library(ggplot2)
```


```{r}

Data <- read.csv("dinosaurus_dozen_clean.csv")
Data |> 
  group_by(dataset) |> 
  summarize(
      mean_x    = mean(x),
      mean_y    = mean(y),
      std_dev_x = sd(x),
      std_dev_y = sd(y),
      corr_x_y  = cor(x, y)
      )

A <- Data |>
  filter(dataset == "a")

shapiro.test(A$x)
shapiro.test(A$y)

B <- Data |>
  filter(dataset == "b")

shapiro.test(B$x)
shapiro.test(B$y)

C <- Data |>
  filter(dataset == "c")

shapiro.test(C$x)
shapiro.test(C$y)

D <- Data |>
  filter(dataset == "d")

shapiro.test(D$x)
shapiro.test(D$y)

E <- Data |>
  filter(dataset == "e")

shapiro.test(E$x)
shapiro.test(E$y)

F <- Data |>
  filter(dataset == "f")

shapiro.test(F$x)
shapiro.test(F$y)

G <- Data |>
  filter(dataset == "g")

shapiro.test(G$x)
shapiro.test(G$y)

H <- Data |>
  filter(dataset == "h")

shapiro.test(H$x)
shapiro.test(H$y)

I <- Data |>
  filter(dataset == "i")

shapiro.test(I$x)
shapiro.test(I$y)

J <- Data |>
  filter(dataset == "j")

shapiro.test(J$x)
shapiro.test(J$y)

K <- Data |>
  filter(dataset == "k")

shapiro.test(K$x)
shapiro.test(K$y)

L <- Data |>
  filter(dataset == "l")

shapiro.test(L$x)
shapiro.test(L$y)

M <- Data |>
  filter(dataset == "m")

shapiro.test(M$x)
shapiro.test(M$y)
```

```{r}
Data |>
  ggplot(aes(x = x, colour = dataset)) +
    geom_boxplot() +
    theme_void() +
    theme(legend.position = "none") +
    facet_wrap(~dataset, ncol = 3)
```

```{r}
Data |>
  ggplot(aes(x = y, colour = dataset))+
    geom_boxplot()+
    theme_void()+
    theme(legend.position = "none")+
    facet_wrap(~dataset, ncol = 3)
```

```{r}
Data |> 
  ggplot() +
  aes(x = x, color = dataset, fill = dataset) +
  geom_histogram() +
  facet_wrap(~dataset)+
  theme_cowplot()
```

```{r}
Data |> 
  ggplot() +
  aes(x = y, color = dataset, fill = dataset) +
  geom_histogram() +
  facet_wrap(~dataset)+
  theme_cowplot()
```


```{r}
Data |> 
  ggplot() +
  aes(x = x,  fill = dataset) + 
  geom_density(alpha=.3) +
  facet_wrap(~dataset)
  theme_cowplot()
```

```{r}
Data |> 
  ggplot() +
  aes(x = y,  fill = dataset) + 
  geom_density(alpha=.3) +
  facet_wrap(~dataset)
  theme_cowplot()
```

```{r}
Data |> 
  ggplot(aes(x = x, y = y, colour = dataset))+
    geom_point()+
    theme_void()+
    theme(legend.position = "none")+
    facet_wrap(~dataset)
```

